#!/bin/bash
machine ls | sed -e 's/\*//' | awk '{print "${alignc}" $1 " - " $3}' | tail -n+2 > raw_machines

if [ $(cat ./raw_machines | wc -l) -eq 0 ]; then
	echo "\${alignc}None"
else
	cat ./raw_machines
fi
